### ISSUE TITLE
Add 4.x versions?

### ISSUE THREAD

**Issue by mastef** [HaxeFoundation/docker-library-haxe#4]
Add haxe 4.x versions? ( But don't tag as `:latest` )

**Comment by andyli** [comment]
Good idea. Worked on it a bit and will finish it soon. :)

**Comment by mastef** [comment]
Nice! What do you think, should there be a -preview.1, -preview.2 ? I'm kind of still running on the pre-preview version of 4.0.0 (git build nightly-travis @ 212f0cd) as it didn't have many breaking changes yet 😅

**Comment by andyli** [comment]
I don't think I will add preview1. The common practice is to only maintain the latest versions of each minor releases - 3.4.x, 4.0.x, 4.1.x etc.
Given preview1 is not even a stable release, so the HF will never fix bug or develop it in general, I will just create the later preview/beta/rc when they come and point 4.0 to that.

**Comment by andyli** [comment]
It's there now: https://hub.docker.com/r/library/haxe/tags/
