### ISSUE TITLE
Warning:Standard library not found

### ISSUE THREAD

**Issue by mastef** [HaxeFoundation/docker-library-haxe#5]
If you had a `ENV HAXE_STD_PATH /usr/local/lib/haxe/std` set before in your child `Dockerfile` be aware that the `HAXE_STD_PATH` is set now in the `haxe:*` containers and was changed to `/usr/local/share/haxe/std`

https://github.com/HaxeFoundation/docker-library-haxe/commit/bd35f9b9c7dfdde69683ac13f12b6786b8eea15d#diff-02aaf2caa0493eb06af310baf8815710

So overriding it with a wrong path may cause the error in the title.

**Comment by andyli** [comment]
I wonder why would one set HAXE_STD_PATH? It should not be necessary for versions other than 3.4.5...

**Comment by mastef** [comment]
I don't recall correctly. Either it was needed for compiling `lime` or `hxcpp`, or `haxelib run lime rebuild hxcpp linux -static`. It's too far down the rabbit hole. Maybe it was a left-over from a base-image switch.
